name = "KidneyExchange"
uuid = "1df6b590-2fd9-4ca0-856d-9bec1eeace35"
authors = ["Jérémy <jeremy.omer@insa-rennes.fr> and contributors"]
version = "0.1.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
GLPK = "60bf3e95-4087-53dc-ae20-288a0d20c6a6"
GR_jll = "d2c73de3-f751-5644-a686-071e5b155ba9"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[compat]
DocStringExtensions = "0.9"
Graphs = "1"
HiGHS = "1"
JuMP = "1"
Requires = "1"
TimerOutputs = "0.5"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
