name = "KidneyExchange"
uuid = "1df6b590-2fd9-4ca0-856d-9bec1eeace35"
authors = ["Jérémy <jeremy.omer@insa-rennes.fr> and contributors"]
version = "0.1.0"

[deps]
Cbc = "9961bab8-2fa3-5c5a-9d89-47fab24efd76"
Clp = "e2554f3b-3117-50c0-817c-e040a3ddf72d"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
GLPK = "60bf3e95-4087-53dc-ae20-288a0d20c6a6"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[compat]
Graphs = "1"
Clp = "0.9"
JuMP = "0.22"
Requires = "1"
Cbc = "0.9"
GLPK = "0.15"
TimerOutputs = "0.5"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
